In [65]:
import pandas as pd 
import numpy as np

In [66]:
bk = pd.read_parquet("airplane_data/bookings_2021.parquet", engine="fastparquet")
ckn = pd.read_parquet("airplane_data/checkins_2021.parquet", engine="fastparquet")
bk.columns

Index(['booking_id', 'customer_id', 'planning_id', 'booking_date', 'trip_type',
       'num_adults', 'num_children', 'num_infants', 'booking_class',
       'booking_status', 'group_booking_type', 'is_charter', 'cancelled_date',
       'rescheduled_date', 'on_hold_date', 'on_hold_end_date', 'outbound_id',
       'rescheduled_id', 'seat_request', 'price_per_ticket', 'is_priority',
       'is_assisted', 'is_special_needs', 'is_lounge_access',
       'is_cancellation_refundable', 'is_travel_protection',
       'is_cheap_hotel_accommodation', 'is_car_rental'],
      dtype='object')

In [67]:
ckn.columns

Index(['checkin_id', 'booking_id', 'planning_id', 'customer_id',
       'passenger_name', 'passenger_type', 'checkin_status', 'gate_number',
       'seat_allocation', 'max_luggage', 'checkin_luggage', 'checkin_time',
       'booking_class', 'group_booking_type', 'total_flight_passengers'],
      dtype='object')

In [68]:
bk2 = bk[['booking_id', 'planning_id', 'num_adults', 'num_children', 'num_infants']].copy()
ckn2 = ckn[['booking_id', 'planning_id', 'customer_id']].copy()

In [69]:
bk2['total_pass'] = bk2['num_adults'] + bk2['num_children'] + bk2['num_infants']
grp = bk2.groupby('planning_id')['total_pass'].sum().reset_index(name='total_passengers')
grp.head()

   planning_id  total_passengers
0  PLN20210001                77
1  PLN20210002                76
2  PLN20210003                75
3  PLN20210004                75
4  PLN20210005                76

In [70]:
grp2 = ckn2.groupby('planning_id').size().reset_index(name='total_checkin_passengers')
grp = grp.merge(grp2, on='planning_id', how='left')
grp.sort_values(by='total_checkin_passengers').head()

      planning_id  total_passengers  total_checkin_passengers
6346  PLN20216347                76                        23
4567  PLN20214568                75                        26
6366  PLN20216367                75                        27
375   PLN20210376                75                        29
6531  PLN20216532                76                        31